### ISSUE TITLE
Create Contacts link on web build does not work

### ISSUE THREAD

**Issue by eshnil** [gskinnerTeam/flokk#13]
![image](https://user-images.githubusercontent.com/51651338/87093164-429a9d00-c22c-11ea-8eea-7cc1c2930cf7.png)

Clicking on "Create Contacts" does nothing. Tested on Flokk.app

**Comment by andyzimmerer** [comment]
Thanks

**Comment by cenomla** [comment]
Duplicate of https://github.com/gskinnerTeam/flokk/issues/35
