### ISSUE TITLE
Clicking on social media icons brings up a window for entering both

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [gskinnerTeam/flokk#17]
<img width="384" alt="Screen Shot 2020-07-14 at 6 48 25 PM" src="https://user-images.githubusercontent.com/23037821/87493888-9decd680-c602-11ea-843c-86c90e023b2c.png">

**Comment by esDotDev** [comment]
This is by design.

**Comment by ThinkDigitalSoftware** [comment]
Oh, I don't feel that there should be 2 buttons do the same thing
