### ISSUE TITLE
Couldn't `flutter pub get`

### ISSUE THREAD

**Issue by gagarin55** [gskinnerTeam/flokk#19]
Hello,
After `flutter pub get` I've got such error:

```
Because dartx >=0.2.0 depends on collection >=1.14.11 <1.15.0 and every version of flutter from sdk depends on collection 1.15.0-nullsafety, dartx >=0.2.0 is incompatible with flutter from sdk.
So, because flokk depends on both flutter any from sdk and dartx ^0.4.0, version solving failed.
pub get failed (1; So, because flokk depends on both flutter any from sdk and dartx ^0.4.0, version solving failed.)
```

I have

```
$ flutter --version
Flutter 1.20.0-8.0.pre.125 • channel master • https://github.com/flutter/flutter.git
Framework • revision 9c4a5ef1ed (9 hours ago) • 2020-07-15 21:41:27 +0100
Engine • revision 774ae0313d
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 89fe12b12a)
```

**Comment by trevordunn** [comment]
The latest version of Flokk was built using commit `9c3f0faa6d` from Flutter's `master` branch (in the readme). If you'd like to use a newer version of Flutter, feel free to submit a PR with the update. Make sure to test the web build and at least the desktop platform you're on...sometimes the runners and other packages need updating too.

**Comment by andyzimmerer** [comment]
_![image](https://user-images.githubusercontent.com/67023680/90343651-d96c2d80-e012-11ea-96d5-d5c2b8be10b7.jpeg)_
