### ISSUE TITLE
experiences imitate

### ISSUE THREAD

**Issue by jinfagang** [gskinnerTeam/flokk#20]
Hi, wanna ask how do u guys implement solved the SQL problem in flokk on desktop version. AFAIK, there were no such plugin for sqflite for now in flutter.

**Comment by esDotDev** [comment]
Simple fix, we didn't use SQL :p

**Comment by jinfagang** [comment]
@esDotDev Tricky. Hard to query or search though.

**Comment by esDotDev** [comment]
Not too bad, in our case we just needed a basic Select and OrderBy functionality, which is fairly easily emulated in code: 
https://github.com/gskinnerTeam/flokk/blob/99d9f3fb771cfc3e32cb329a7ba6233cc7ea8f96/flokk_src/lib/views/search/search_engine.dart#L142

Not  as nice to read as a simple SQL query, but gets the job done.
