### ISSUE TITLE
Unable to copy text

### ISSUE THREAD

**Issue by rish07** [gskinnerTeam/flokk#29]
Hey,
I'm trying to make a flutter desktop app for Linux and in a text field, I'm not able to use any keyboard shortcuts for eg, ctrl+c for copy or ctrl+a for all selection. Can you help me with this?

**Comment by YehudaKremer** [comment]
yep, the flokk app for the web also not enabling to select texts.

please see this solution: https://github.com/flutter/flutter/issues/32246#issuecomment-546485253
