### ISSUE TITLE
README gives incorrect Flutter hash

### ISSUE THREAD

**Issue by stuartmorgan** [gskinnerTeam/flokk#31]
The recent changes to the repo appear to be using a recent master—it's using the latest FDE plugin versions, and a fairly recent version of the Windows runner—but the README still says to use Flutter 9c3f0faa6d, which is from June. That wouldn't compile.

The README should be updated to whatever version you updated against.

**Comment by trevordunn** [comment]
Thanks for pointing this out. Fixed here: 861553120f153a6cba8bf262d6fc02002234469b
