### ISSUE TITLE
Provide an .exe file so people could try the app on their pcs

### ISSUE THREAD

**Issue by fisforfaheem** [gskinnerTeam/flokk#4]
i use windows 10 and want a simple way to open the app, so please provide a .exe file

**Comment by trevordunn** [comment]
Hi @fisforfaheem, you can find a download for that in the readme https://github.com/gskinnerTeam/flokk#demo-builds. I'll look into adding this info to the release as well.

**Comment by fisforfaheem** [comment]
Hope to get the .exe file udate soon
