### ISSUE TITLE
Empty window on Ubuntu 20.04

### ISSUE THREAD

**Issue by mivoligo** [gskinnerTeam/flokk#8]
Just installed the snap version. After starting the app, I can only see an empty window. When I start the app from terminal I get this:
```
michal@michal-laptop:~$ flokk-contacts 

(flokk-contacts:3482): Gdk-WARNING **: 09:52:42.440: ../../../../../gdk/x11/gdkwindow-x11.c:5579 drawable is not a native X11 window

** (flokk-contacts:3482): WARNING **: 09:52:42.450: Failed to start Flutter engine: Failed to create EGL surface: Bad Native Window
```

**Comment by maks** [comment]
This is actually because you are using Wayland and currently [Wayland is not working in Flutter Linux Desktop](https://github.com/flutter/flutter/issues/57932)

**Comment by mivoligo** [comment]
Thanks @maks That's true. It works fine when not using Wayland.
